[package]
name = "twabbit"
version = "0.1.0"
edition = "2021"
authors = ["Thao D <ardtimeit@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
typed-arena = "2.0"
